language: cpp

git:
  depth: 1

branches:
  only:
    - master

compiler:
  - gcc

before_install:
  - sudo apt-get install libace-dev
  - sudo apt-get install libncurses5-dev
  - sudo apt-get install build-essential autoconf libtool gcc g++ make cmake git-core patch wget links zip unzip unrar
  - sudo apt-get install openssl libssl-dev mysql-server mysql-client libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  
script:
  - mkdir build
  - cd build
  - cmake .. -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=0 -DSCRIPTS=1 -DSERVERS=1
  - make -j16

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    channels:
      - "irc.rizon.net#bloodcraft-staff"
      - "irc.bloodcraft.org#dev"
    channel_key: 'in5RPn'
    on_success: always
    on_failure: always
