language: cpp

git:
  depth: 1

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y 
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libtool gcc-4.9 g++-4.9 make cmake openssl libssl-dev libmysqlclient15-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libboost1.55-dev libboost-thread1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev
  
script:
  - mkdir build
  - cd build
  - declare -x CFLAGS="-std=c++11"
  - declare -x CXXFLAGS="-std=c++11"
  - cmake .. -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=0 -DSCRIPTS=1 -DSERVERS=1
  - make -j16

notifications:
  email: false
  webhooks:
    urls:
      - http://irc.truewow.org:8080/travis
    on_success: always
    on_failure: always
    on_start: always
